# Generated by Django 5.2.3 on 2025-06-16 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0006_alter_sale_intermediary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.business')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date'],
                'managed': True,
            },
        ),
    ]
