# Generated by Django 5.2.3 on 2025-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='business_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_id',
            field=models.IntegerField(default=1),
        ),
    ]
