# Generated by Django 5.2.3 on 2025-06-15 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_business_alter_sale_business_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='business_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_id', to='reports.business'),
        ),
    ]
