# Generated by Django 5.2.3 on 2025-06-15 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_sale_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.business'),
        ),
    ]
