# Generated by Django 5.2.3 on 2025-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='intermediary',
            field=models.CharField(default='Oficina', max_length=50),
        ),
    ]
