# Generated by Django 5.2.3 on 2025-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_sale_notes_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='passport',
            field=models.CharField(default='', max_length=50),
        ),
    ]
