# Generated by Django 5.2.3 on 2025-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_sale_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='payed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='Residente', max_length=50),
        ),
    ]
