# Generated by Django 5.2.3 on 2025-06-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_sale_mail_sale_payed_sale_payment_sale_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payed',
        ),
    ]
