# Generated by Django 5.2.3 on 2025-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_sale_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
