# Generated by Django 5.2.3 on 2025-07-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_sale_payed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.business')),
            ],
            options={
                'db_table': 'owner',
                'managed': True,
            },
        ),
    ]
