# Generated by Django 5.2.3 on 2025-07-04 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_capacity', models.PositiveIntegerField()),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('responsible_name', models.CharField(max_length=100)),
                ('responsible_passport', models.CharField(max_length=20)),
                ('responsible_phone', models.CharField(max_length=15)),
                ('captain_name', models.CharField(max_length=100)),
                ('captain_password', models.CharField(max_length=20)),
                ('sailor1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sailor1_passport', models.CharField(blank=True, max_length=20, null=True)),
                ('sailor2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sailor2_passport', models.CharField(blank=True, max_length=20, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.business')),
            ],
            options={
                'verbose_name': 'Tripulación',
                'verbose_name_plural': 'Tripulaciones',
            },
        ),
    ]
