# Generated by Django 5.2.3 on 2025-07-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_crew_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='crew',
            table='crew',
        ),
    ]
