# Generated by Django 5.2.3 on 2025-07-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_crew_options_alter_crew_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='business',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
