# Generated by Django 5.2.3 on 2025-07-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_remove_owner_business_delete_crew_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferry_name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferries', to='reports.business')),
            ],
            options={
                'db_table': 'ferry',
                'managed': True,
            },
        ),
    ]
