# Generated by Django 5.2.3 on 2025-07-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtoken',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
