# Generated by Django 5.2.3 on 2025-07-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registrationtoken_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationtoken',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='registrationtoken',
            table='registration_token',
        ),
    ]
