# Generated by Django 5.2.3 on 2025-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registrationtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='business',
            field=models.CharField(default='', max_length=255),
        ),
    ]
