# Generated by Django 5.2.3 on 2025-07-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='captain_password',
            new_name='captain_passport',
        ),
    ]
