# Generated by Django 5.2.3 on 2025-07-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_captain_password_crew_captain_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='ferry_registration',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
