# Generated by Django 5.2.3 on 2025-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_crew_ferry_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='responsible_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
