# Generated by Django 5.2.3 on 2025-06-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinates',
            options={'managed': True, 'ordering': ['-time']},
        ),
    ]
